### ISSUE TITLE
cp?

### ISSUE THREAD

**Issue by DZuz14** [littleindianboy/react-express-template#1]
"start" : "webpack -d && cp src/index.html www/index.html && nodemon",

What does the cp command do in this part? It gives me an error as not recognized and the server won't boot up.

**Comment by saagarvaru** [comment]
It should copy the file from the src folder to the www folder    I'll look at it when I get home tonight.   
- Saagar

**Comment by saagarvaru** [comment]
I've also found an easier way to do it, I'll push it tonight

**Comment by saagarvaru** [comment]
I just pushed an update, give it a try and let me know if it works :)

**Comment by DZuz14** [comment]
Pulling now!

**Comment by DZuz14** [comment]
Okay so I had to change my start script to this,

`"start" : "node ./server/server.js"`

On my system it needed that extra "." in front of the forward slash. It's up and running. I'm going to close this comment but will open more if theres a problem.
